### ISSUE TITLE
RuntimeError: No suitable key found in keytab.

### ISSUE THREAD

**Issue by joakim-tjernlund** [ufven/cepces#11]
I get 3-4 of these each time I boot
```
2020-05-19 17:43:25,014 __main__:ERROR:Traceback (most recent call last):
  File "/usr/libexec/certmonger/cepces-submit", line 61, in main
    config = Configuration.load()
  File "/usr/lib64/python3.6/site-packages/cepces/config.py", line 131, in load
    return Configuration.from_parser(config)
  File "/usr/lib64/python3.6/site-packages/cepces/config.py", line 169, in from_parser
    return Configuration(endpoint, endpoint_type, cas, authn.handle())
  File "/usr/lib64/python3.6/site-packages/cepces/auth.py", line 94, in handle
    raise RuntimeError('No suitable key found in keytab.')
RuntimeError: No suitable key found in keytab.
```
How to log better here(I don't do python)?

**Comment by joakim-tjernlund** [comment]
Error is raised when there is no network yet.
Should it relally do that or just wait a bit and then try again ?

**Comment by ufven** [comment]
I think certmonger is trying too early. This error should probably be caught earlier, and the trace suppressed. I'll see if I can handle it better.
